services:
  # HTTP Transcription Service (General Model) - This service uses the shared image.
  qwen2.5-omni-http:
    build:
      context: .
      dockerfile: Dockerfile
    image: qwen2.5-omni-app:latest
    container_name: qwen2.5-omni-http
    ports:
      - "5020:5000"
      - "5021:7860"
    volumes:
      - ./app/serve:/app/serve
      - ./app/inputs:/app/inputs
      - ./app/temp:/app/temp
      - ./app/outputs:/app/outputs
      - ./app/Qwen:/app/Qwen
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: [
      "python3", "serve/qwen2_5_omni.py",
      "--checkpoint-path", "Qwen/Qwen2.5-Omni-7B",
      "--host", "0.0.0.0",
      "--port", "5000",
      "--server-name", "0.0.0.0",
      "--server-port", "7860",
      "--flash-attn2",
      "--segment-duration", "15",
      "--max-new-tokens", "8192",
      "--temperature", "0.1",
      "--repetition-penalty", "1.1",
      "--idle-timeout", "600"
    ]
    environment:
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    networks:
      - qwen_network

networks:
  qwen_network:
    driver: bridge
